name: CDK DEPLOY

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         repository: a-Coppens/CodingTest-CDK
         path: './CodingTest-CDK'
         
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: a-Coppens/JavaCodingTest
          
        
      - name: list files
        run: |
         cd ..
         cd ..
         cd ..
         find . 

   #   - name: Build Docker Image
  #      run: |
     #    docker build -f src/main/docker/Dockerfile -t adamcoppens/coding-test-app .
         
     # docker -d -g /home/user1/docker          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

   #   - name: install npm
   #     run: 'sudo apt update -y && sudo apt install nodejs npm -y'
        
   #   - name: Install AWS CDK
   #     run: 'sudo npm install -g aws-cdk'
        
  #    - name: install npm dependencies
   #     run: 'npm install'
        
   #   - name: list files
  #      run: |
  #    
   #       ls -d
  #      #cdk deploy --app ./CodingTest-CDK/cdk.out --require-approval never "*"
  #    - name: Deploy CDK
   #     run: |
   #        cdk deploy 
  #      env:
   #        AWS_REGION: ap-southeast-2
   #        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
