name: CDK DEPLOY

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
         repository: a-Coppens/CodingTest-CDK
         path: './CodingTest-CDK'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'
        
      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'
        
        ## TODO : CDK SYNTH
      - name: Synth CDK
	run:
	  cdk synth --require-approval never "*"

      - name: Deploy CDK
        run: |
          cdk deploy --app ./CodingTest-CDK/cdk.out --require-approval never "*"
        env:
          AWS_REGION: ap-southeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
